### PR TITLE
Remove unnecessary backslashes in regex to satisfy flake8.

### PR DESCRIPTION
**Pull request by worldwise001**
### Summary of Changes

Another small PR. Backslashes are not required within [] because most characters are interpreted as literals. Removing these backslashes satisfies more stringent flake8 style checks.

### Tests

None needed, small text change.

### Documentation

None needed, small text change.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes. 
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [X] PR passes `make test`
- [X] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by worldwise001** [comment]
Another tiny change from doing merge conflict resolution from upstream.

**Comment by feng-tao** [comment]
@worldwise001 thanks. Could you bump the minor version of the change as well?

**Comment by feng-tao** [comment]
also curious given we have flake8 running for this repo, is your local / private repo having a different or stringent flake8 rule?

**Comment by worldwise001** [comment]
I believe we have more stringent flake8 rules. I can bump the minor version of the change too.

**Comment by feng-tao** [comment]
@worldwise001 , please do. Thanks:)

**Comment by feng-tao** [comment]
I try it out which the wildcard search still works with the change. So I think it should be fine. Thanks @worldwise001 :)

**Pull request merged**
