### PR TITLE
[Bug Fix] Splits the document APIs into two objects. 

### PR DESCRIPTION
**Pull request by swatro**
Splits the document APIs into two objects. One for operations that act on resource collections and one for operations that act on individuals items in the resource collection.

### Summary of Changes

I came across the following bug while putting together documentation for the Search Service API. This bug is not "mission critical". However, the Swagger documentation is looking at all the endpoints and methods setup in Flask, so this bug was causing the Swagger documentation to give users bad information. 😞 

#### How to reproduce the bug: 
Request: `curl -X PUT http://localhost:5000/document_table/id` 
Response: `{ "message": "Internal Server Error"}`
Log Error: 
```
ERROR:flask.app:Exception on /document_table/id [PUT]
Traceback (most recent call last):
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: put() got an unexpected keyword argument 'document_id'
```

Request: `curl -X DELETE http://localhost:5000/document_table`
Response: `{ "message": "Internal Server Error"}`
Log Error Message: 
```
ERROR:flask.app:Exception on /document_table [DELETE]
Traceback (most recent call last):
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/swatro/code/amundsensearchlibrary/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: delete() missing 1 required keyword-only argument: 'document_id'
INFO:werkzeug:127.0.0.1 - - [19/Sep/2019 15:07:21] "DELETE /document_table HTTP/1.1" 500 -
```

#### Why is this happening?
These lines of code in the service init file are the problem. This code is adding the resource to Flask and allowing all methods to be accessed via both URLs. However, both URLs are not supported by our methods.
```
api.add_resource(DocumentTableAPI, '/document_table', '/document_table/<document_id>') 
api.add_resource(DocumentUserAPI, '/document_user', '/document_user/<document_id>')
```

#### This solution
To solve this problem, I followed this [documentation](https://flask-restful.readthedocs.io/en/latest/quickstart.html#full-example) and split the operations into two classes. Now the init file looks like this:  
```
    api.add_resource(DocumentTablesAPI, '/document_table')
    api.add_resource(DocumentTableAPI, '/document_table/<document_id>')

    api.add_resource(DocumentUsersAPI, '/document_user')
    api.add_resource(DocumentUserAPI, '/document_user/<document_id>')
```

Now the following works: 
Request: `curl -X DELETE http://localhost:5000/document_table`
Response: `{ "message": "The method is not allowed for the requested URL." }`

### Tests

Most of the unit tests are the ones that already existed for this functionality. I did add a couple of unit tests that verify we get a 405 instead of a 500. These tests are probably overkill, but it helped me to verify the problem was fixed.

### Documentation

Don't think we need any. 

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes `make test`

### CODE REVIEW

**Comment by feng-tao** [comment]
@alran would you mind taking a look given you are the original author of the document API?

**Comment by swatro** [comment]
@feng-tao works for me. I'll make that change.

**Comment by feng-tao** [comment]
thanks a lot @swatro !

**Comment by swatro** [comment]
@feng-tao I did split out the tests, same way I split out the table tests. It's allowing out test objects to be smaller, which I think is nice. But I can also see it being confusing.

**Comment by feng-tao** [comment]
thanks a lot @swatro

**Comment by alran** [comment]
Sorry @feng-tao I was on vacation last week!

**Pull request merged**
