### PR TITLE
Add user document endpoint

### PR DESCRIPTION
**Pull request by alran**
### Summary of Changes

This PR creates an endpoint for updating the user index in elasticsearch. The document endpoint previously only supported table document updates.

### Tests

I added tests for the api endpoint to match the tests I made previously for table documents

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes `make test`
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

CC @feng-tao

### CODE REVIEW

**Comment by jornh** [comment]
Haha, GREAT looks like I/@feng-tao should hold the horses a bit with https://github.com/lyft/amundsendatabuilder/pull/130 - and specifically https://github.com/lyft/amundsendatabuilder/pull/130#issuecomment-520694270 🙂 to align with this?

Seems Databuilder don't need to know the "ES implementation details" any more if I understand this correctly? ... and that it just need to post K/V pairs similar to what's in https://github.com/lyft/amundsensearchlibrary/pull/40#issue-299047415 - right?

**Comment by alran** [comment]
@jornh yep, thats what I'm trying to achieve! We are trying to get away from having our databuilder need to know such specific things about how search works. 

At Square, we end up with code like:

```
def refresh_elasticsearch(self, data: list, schema: Any, doc_type: str = 'table') -> None:
   dump: MarshalResult = schema(many=True, strict=True).dumps(data).data
   URL = f'{<our search service base>}/document_{doc_type}'
   response: Response = send(url=URL, method='POST', data=json.dumps({'data': dump}), config=self.config)

...

data = [dict(email='test@email.com', name='sarah')]
refresh_elasticsearch(data=data, schema=UserSchema, doc_type='user')
```

**Comment by jornh** [comment]
Neat! To take it to the extreme maybe you could even argue that updating search could be hidden "behind" the metadata service - so POST/PUT of metadata (from either frontend, databuilder or other parties) would make metadata update search? 

I can't think of cases where search shouldn't follow metadata ...

This would AFAICT also tick the last box in https://github.com/lyft/amundsen/issues/52#issuecomment-500339360 - or am I overlooking something?

**Comment by alran** [comment]
yes, it does tick that last box! I should have just pushed all this code with my first PR, but we hadn't wired up users yet on our end

**Comment by jornh** [comment]
No worries - as long as we are moving nicely forward, which this definitely is!

**Comment by jornh** [comment]
Excited to see this going in! This means I can revise my Databuilder PR to not expose the inner workings of Amundsen search.

A nit, or rather a question for future consideration  - please don’t block on this :-), is Amundsen doing semantic versioning for the services? If so with an extension of the api like here I guess it would actually mean a bump to `v1.2.0`?

Is there a better place to discuss this?

Also, I think it would be a pity to not surface the nice usage docco in #40 - but that can easily be a follow up PR 🙂

**Pull request merged**
