### PR TITLE
Revert to proper Table key rendering (AtlasProxy)

### PR DESCRIPTION
**Pull request by mgorsk1**
### Summary of Changes

This PR reverts the change with rendering `key` field in Table object.

Having key in previous format is required for amundsenmetadatalibrary features like bookmarks to work properly.

### Tests

Adjusted tests and run to completion.

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes `make test`

### CODE REVIEW

**Comment by mgorsk1** [comment]
cc @verdan

**Comment by feng-tao** [comment]
cc @verdan

**Comment by mgorsk1** [comment]
it can be done totally independently

**Comment by feng-tao** [comment]
thanks!

**Pull request merged**
