### PR TITLE
fix for issue 106

### PR DESCRIPTION
**Pull request by javamonkey79**
### Summary of Changes

* changes field value factor from log1p to log2p to fix an issue with missing usage data

### CODE REVIEW

**Comment by feng-tao** [comment]
hey @javamonkey79, could you also bump the version? Thanks.

**Comment by javamonkey79** [comment]
Sure @feng-tao I bumped the minor version, I hope that's what you mean.

**Comment by feng-tao** [comment]
thanks @javamonkey79

**Comment by javamonkey79** [comment]
Happy to help @feng-tao , thanks for helping me get it merged in so quick!

**Pull request merged**
